/**
 * ascensionPeonjdialog.java
 * 
 * Mayo 2019
 * 
 * realizado por Ana Sofia Beltran Rios 1004716847
 * @author utp: odau
 */
package co.edu.utp.isc.pro4.ajedrez.ui;

/** clase ascensionPeonjdialog, cuya funcion es manejar la visualizacion de la casilla para elegir la ascension del peon */
public class ascensionPeonjdialog extends javax.swing.JDialog {
    
    //Variable
    String casilla;
    /**
     * Creates new form ascensionPeonjdialog
     */
    public String getCasilla(){
        return casilla;
    }
    public ascensionPeonjdialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        reina = new javax.swing.JButton();
        alfil = new javax.swing.JButton();
        torre = new javax.swing.JButton();
        caballo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setText("¿A que ficha quiere cambiar el peon?");

        reina.setText("Reina");
        reina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reinaActionPerformed(evt);
            }
        });

        alfil.setText("Alfil");
        alfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alfilActionPerformed(evt);
            }
        });

        torre.setText("Torre");
        torre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torreActionPerformed(evt);
            }
        });

        caballo.setText("Caballo");
        caballo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caballoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(55, 55, 55))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(reina)
                .addGap(0, 0, 0)
                .addComponent(alfil)
                .addGap(6, 6, 6)
                .addComponent(torre)
                .addGap(6, 6, 6)
                .addComponent(caballo)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reina)
                    .addComponent(alfil)
                    .addComponent(torre)
                    .addComponent(caballo))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reinaActionPerformed
        casilla="reina";
        dispose();
    }//GEN-LAST:event_reinaActionPerformed

    private void alfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alfilActionPerformed
        casilla="alfil";
        dispose();
    }//GEN-LAST:event_alfilActionPerformed

    private void torreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torreActionPerformed
        casilla="torre";
        dispose();
    }//GEN-LAST:event_torreActionPerformed

    private void caballoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caballoActionPerformed
        casilla="caballo";
        dispose();
    }//GEN-LAST:event_caballoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ascensionPeonjdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ascensionPeonjdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ascensionPeonjdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ascensionPeonjdialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ascensionPeonjdialog dialog = new ascensionPeonjdialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alfil;
    private javax.swing.JButton caballo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton reina;
    private javax.swing.JButton torre;
    // End of variables declaration//GEN-END:variables
}
